import { RepoSeatbeltConfig } from '../types';

export function generateAgentsMd(config: RepoSeatbeltConfig, lang: 'en' | 'tr' = 'en'): string {
  const isEn = lang === 'en';
  const mode = config.mode;

  const protectedList = config.protectedFiles.map(f => `- \`${f}\``).join('\n');
  const approvalList = config.approvalRequired.map(f => `- \`${f}\``).join('\n');
  const blockedList = config.blockedCommands.map(c => `- \`${c}\``).join('\n');
  const tools = config.selectedTools.length > 0 ? config.selectedTools.join(', ') : 'All AI tools';

  if (isEn) {
    return `# AI Agent Safety Rules

> Generated by [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt) · Mode: ${mode} · Tools: ${tools}

This file defines safety rules for AI coding agents working in this repository.
**Read and follow these rules before making any changes.**

---

## Core Rules

1. **Do not modify \`.env\` files** - environment variables must be managed manually by the developer
2. **Do not delete or modify migration files** - database migrations are critical and often irreversible
3. **Do not modify auth or payment files** without explicit developer approval
4. **Do not run destructive commands** - see the blocked commands list below
5. **Prefer small, focused changes** - avoid large refactors unless explicitly asked
6. **Do not add new dependencies** unless the developer asks for them
7. **Explain risky changes before applying** - if a change touches protected files, ask first
8. **Check existing patterns first** - before creating new utilities, check if one exists
9. **Do not rewrite unrelated files** - stay focused on the requested task
10. **Do not change production configuration** without explicit approval${mode === 'team' ? `
11. **Include test coverage** for any new logic you add
12. **Update relevant documentation** when changing interfaces or APIs` : ''}${mode === 'strict' ? `
11. **Treat all database, auth, and payment areas as blocked** unless explicitly unblocked
12. **Never run scripts** from package.json without showing them to the developer first
13. **Request approval for every file** in the approvalRequired list` : ''}

---

## Protected Files (Do Not Modify)

${protectedList || '- *(none configured)*'}

---

## Files Requiring Explicit Approval

These files require the developer to say "go ahead" before you touch them:

${approvalList || '- *(none configured)*'}

---

## Blocked Commands

Never run these commands without explicit approval:

${blockedList || '- *(none configured)*'}

---

## General Guidance

- **If uncertain, ask.** A small interruption is better than a hard-to-reverse mistake.
- **Small commits are better.** Prefer incremental changes over large rewrites.
- **Test before finishing.** If tests exist, run them before declaring the task complete.
- **Rollback plan.** Before making risky changes, consider how to undo them.

---

## Project Info

- **Safety mode:** ${mode}
- **Project type:** ${config.projectType}
- **Language:** ${lang}

*This file was generated by [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt). Keep it up to date as your project grows.*
`;
  }

  // Turkish
  return `# AI Agent Güvenlik Kuralları

> [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt) tarafından oluşturuldu · Mod: ${mode} · Araçlar: ${tools}

Bu dosya, bu depoda çalışan AI kodlama agent'ları için güvenlik kurallarını tanımlar.
**Herhangi bir değişiklik yapmadan önce bu kuralları okuyun ve uygulayın.**

---

## Temel Kurallar

1. **\`.env\` dosyalarını düzenlemeyin** - ortam değişkenleri geliştirici tarafından manuel olarak yönetilmelidir
2. **Migration dosyalarını silmeyin veya değiştirmeyin** - veritabanı migration'ları kritik ve genellikle geri alınamaz
3. **Auth veya ödeme dosyalarını** geliştirici onayı olmadan değiştirmeyin
4. **Yıkıcı komutları çalıştırmayın** - aşağıdaki engellenen komutlar listesine bakın
5. **Küçük, odaklı değişiklikler tercih edin** - açıkça istenmediği sürece büyük refaktörden kaçının
6. **Gerekmedikçe yeni bağımlılık eklemeyin** - geliştirici istemedikçe
7. **Riskli değişiklikleri uygulamadan önce açıklayın** - korunan dosyalara dokunan bir değişiklik için önce sorun
8. **Önce mevcut kalıpları kontrol edin** - yeni araçlar oluşturmadan önce var olan bir tane olup olmadığını kontrol edin
9. **İlgisiz dosyaları yeniden yazmayın** - istenen göreve odaklanın
10. **Üretim yapılandırmasını** açık onay olmadan değiştirmeyin${mode === 'strict' ? `
11. **Tüm veritabanı, auth ve ödeme alanlarını engelli kabul edin** - açıkça serbest bırakılmadıkça
12. **package.json'daki script'leri** önce geliştiriciye göstermeden çalıştırmayın
13. **approvalRequired listesindeki her dosya için onay isteyin**` : ''}

---

## Korunan Dosyalar (Değiştirmeyin)

${protectedList || '- *(yapılandırılmamış)*'}

---

## Açık Onay Gerektiren Dosyalar

Bu dosyalar için geliştirici "devam et" demeden dokunmayın:

${approvalList || '- *(yapılandırılmamış)*'}

---

## Engellenen Komutlar

Bu komutları açık onay olmadan hiçbir zaman çalıştırmayın:

${blockedList || '- *(yapılandırılmamış)*'}

---

## Genel Rehberlik

- **Emin değilseniz sorun.** Küçük bir kesinti, geri alınması zor bir hatadan daha iyidir.
- **Küçük commit'ler daha iyidir.** Büyük yeniden yazmalar yerine artımlı değişiklikler tercih edin.
- **Bitirmeden önce test edin.** Test mevcutsa, görevi tamamlamadan önce çalıştırın.
- **Geri alma planı.** Riskli değişiklikler yapmadan önce nasıl geri alınacağını düşünün.

---

## Proje Bilgileri

- **Güvenlik modu:** ${mode}
- **Proje türü:** ${config.projectType}
- **Dil:** ${lang}

*Bu dosya [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt) tarafından oluşturuldu. Projeniz büyüdükçe güncel tutun.*
`;
}
