import { RepoSeatbeltConfig } from '../types';

export function generateAiderConventions(config: RepoSeatbeltConfig, lang: 'en' | 'tr' = 'en'): string {
  const isEn = lang === 'en';
  const protectedList = config.protectedFiles.map(f => `- ${f}`).join('\n');
  const approvalList = config.approvalRequired.map(f => `- ${f}`).join('\n');
  const blockedList = config.blockedCommands.map(c => `- ${c}`).join('\n');

  if (isEn) {
    return `# Aider Conventions

> Generated by repo-seatbelt | Safety mode: ${config.mode}
> Load this file with: \`aider --read CONVENTIONS.md\`

## Protected Files - Do Not Add or Edit
${protectedList}

## Files That Require Explicit Approval
${approvalList}

## Commands You Must Not Run
${blockedList}

## Conventions

- Make the smallest possible change to accomplish the goal
- Match the existing code style of each file
- Do not add new dependencies without asking
- Do not refactor unrelated code
- Always run tests after edits if present
- For migrations, auth, payment, or production config: stop and confirm before editing

## Project: ${config.projectType}
`;
  }

  return `# Aider Conventions

> repo-seatbelt tarafından oluşturuldu | Güvenlik modu: ${config.mode}
> Bu dosyayı şununla yükleyin: \`aider --read CONVENTIONS.md\`

## Korunan Dosyalar - Eklemeyin veya Düzenlemeyin
${protectedList}

## Açık Onay Gerektiren Dosyalar
${approvalList}

## Asla Çalıştırmamanız Gereken Komutlar
${blockedList}

## Konvansiyonlar

- Amacı gerçekleştiren en küçük değişikliği yapın
- Her dosyanın mevcut kod stiline uyum sağlayın
- Sormadan yeni bağımlılık eklemeyin
- İlgisiz kodu refactor etmeyin
- Düzenleme sonrası varsa testleri çalıştırın
- Migration, auth, ödeme veya prod yapılandırması için: düzenlemeden önce durun ve onaylayın

## Proje: ${config.projectType}
`;
}
