import { RepoSeatbeltConfig } from '../types';

export function generateClaudeMd(config: RepoSeatbeltConfig, lang: 'en' | 'tr' = 'en'): string {
  const isEn = lang === 'en';
  const mode = config.mode;

  const protectedList = config.protectedFiles.map(f => `- \`${f}\``).join('\n');
  const approvalList = config.approvalRequired.map(f => `- \`${f}\``).join('\n');
  const blockedList = config.blockedCommands.map(c => `- \`${c}\``).join('\n');

  if (isEn) {
    return `# Claude Code Safety Rules

> Generated by [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt) · Safety mode: \`${mode}\`

## IMPORTANT - Read Before Modifying Anything

This repository is protected by repo-seatbelt. These rules apply to every session.

---

## Do Not Touch Without Permission

The following files and folders are **strictly protected**. Do not read, modify, or delete them unless the developer explicitly says so:

${protectedList || '- *(none configured)*'}

---

## Ask Before Modifying

These areas require explicit developer confirmation before you make changes:

${approvalList || '- *(none configured)*'}

**How to ask:** Say "I need to modify \`[file]\` - is that okay?" and wait for approval.

---

## Never Run These Commands

${blockedList || '- *(none configured)*'}

If you need to run one of these, **explain why and ask for explicit approval** before proceeding.

---

## Safety Mode: ${mode.toUpperCase()}

${mode === 'solo' ? `
- Warnings are advisory, not blocking
- Focus on completing tasks efficiently
- Flag risks, but don't stop unless critical
` : mode === 'team' ? `
- Apply stronger caution around shared code
- Prefer reversible changes
- Always mention when touching auth, payment, or database code
- Suggest PR descriptions for significant changes
` : `
- Treat all database, auth, payment, and prod config as blocked by default
- Require explicit approval for every non-trivial change
- Refuse to run any script without showing it first
- Prefer no-op over risk when uncertain
`}

---

## General Principles

- Make the smallest change that accomplishes the goal
- Preserve existing code style and patterns
- Explain what you're about to do before doing it for risky operations
- If you notice something outside the requested scope, mention it but don't fix it
- Run tests if they exist after making changes

---

## Project Info

\`\`\`json
${JSON.stringify({
  mode: config.mode,
  projectType: config.projectType,
  language: config.language,
  selectedTools: config.selectedTools,
}, null, 2)}
\`\`\`

*This file was generated by [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt). Update it as your project evolves.*
`;
  }

  // Turkish
  return `# Claude Code Güvenlik Kuralları

> [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt) tarafından oluşturuldu · Güvenlik modu: \`${mode}\`

## ÖNEMLİ - Herhangi Bir Şeyi Değiştirmeden Önce Okuyun

Bu depo repo-seatbelt tarafından korunmaktadır. Bu kurallar her oturum için geçerlidir.

---

## İzin Olmadan Dokunmayın

Aşağıdaki dosyalar ve klasörler **kesinlikle korunmaktadır**. Geliştirici açıkça izin vermedikçe okumayın, değiştirmeyin veya silmeyin:

${protectedList || '- *(yapılandırılmamış)*'}

---

## Değiştirmeden Önce Sorun

Bu alanlar, değişiklik yapmanız için geliştiricinin açık onayını gerektirir:

${approvalList || '- *(yapılandırılmamış)*'}

**Nasıl sorulur:** "\`[dosya]\`'yı değiştirmem gerekiyor - uygun mu?" deyin ve onay bekleyin.

---

## Bu Komutları Asla Çalıştırmayın

${blockedList || '- *(yapılandırılmamış)*'}

Bunlardan birini çalıştırmanız gerekiyorsa, devam etmeden önce **neden gerektiğini açıklayın ve açık onay isteyin**.

---

## Güvenlik Modu: ${mode.toUpperCase()}

${mode === 'solo' ? `
- Uyarılar tavsiye niteliğindedir, engelleyici değil
- Görevleri verimli bir şekilde tamamlamaya odaklanın
- Riskleri işaretleyin, ancak kritik olmadıkça durmayın
` : mode === 'team' ? `
- Paylaşılan kod etrafında daha güçlü önlem uygulayın
- Geri alınabilir değişiklikleri tercih edin
- Auth, ödeme veya veritabanı koduna dokunurken her zaman belirtin
` : `
- Tüm veritabanı, auth, ödeme ve prod yapılandırmasını varsayılan olarak engelli kabul edin
- Önemsiz olmayan her değişiklik için açık onay isteyin
- Script'leri önce göstermeden çalıştırmayı reddedin
`}

---

## Genel İlkeler

- Amacı gerçekleştiren en küçük değişikliği yapın
- Mevcut kod stilini ve kalıplarını koruyun
- Riskli işlemler için yapmadan önce ne yapacağınızı açıklayın
- İstenen kapsam dışında bir şey fark ederseniz belirtin ama düzeltmeyin
- Değişiklik yaptıktan sonra testler mevcutsa çalıştırın

---

## Proje Bilgileri

\`\`\`json
${JSON.stringify({
  mode: config.mode,
  projectType: config.projectType,
  language: config.language,
  selectedTools: config.selectedTools,
}, null, 2)}
\`\`\`

*Bu dosya [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt) tarafından oluşturuldu. Projeniz geliştikçe güncelleyin.*
`;
}
