import { RepoSeatbeltConfig } from '../types';

export function generateClineRules(config: RepoSeatbeltConfig, lang: 'en' | 'tr' = 'en'): string {
  const isEn = lang === 'en';
  const protectedList = config.protectedFiles.map(f => `- ${f}`).join('\n');
  const approvalList = config.approvalRequired.map(f => `- ${f}`).join('\n');
  const blockedList = config.blockedCommands.map(c => `- ${c}`).join('\n');

  if (isEn) {
    return `# Cline Rules

Generated by repo-seatbelt | Mode: ${config.mode}

## Protected (do not read/edit/delete)
${protectedList}

## Approval Required Before Editing
${approvalList}

## Never Execute These Commands
${blockedList}

## Behavior
- Make small, surgical edits — never large rewrites without approval
- Always show planned shell commands before executing
- For destructive ops, ask: "Are you sure? This will <effect>" and wait for yes
- Do not install new packages unless asked
- Run available tests after non-trivial changes
${config.mode === 'strict' ? '\n## Strict Mode\n- Default to blocking risky operations\n- Require approval for any change to auth/payment/db/prod' : ''}
`;
  }

  return `# Cline Kuralları

repo-seatbelt tarafından oluşturuldu | Mod: ${config.mode}

## Korunan (okuma/düzenleme/silme yapmayın)
${protectedList}

## Düzenlemeden Önce Onay Gerektirir
${approvalList}

## Asla Bu Komutları Çalıştırmayın
${blockedList}

## Davranış
- Küçük, hedefli düzenlemeler yapın — onay olmadan büyük yeniden yazmalar yok
- Çalıştırmadan önce planlanan shell komutlarını gösterin
- Yıkıcı işlemler için: "Emin misiniz? Bu <etki> yapacak" deyin ve evet bekleyin
- İstenmedikçe yeni paket kurmayın
- Önemli değişikliklerden sonra varsa testleri çalıştırın
${config.mode === 'strict' ? '\n## Katı Mod\n- Riskli işlemleri varsayılan olarak engelle\n- Auth/payment/db/prod değişiklikleri için onay iste' : ''}
`;
}
