import { RepoSeatbeltConfig } from '../types';

export function generateCursorRules(config: RepoSeatbeltConfig, lang: 'en' | 'tr' = 'en'): string {
  const isEn = lang === 'en';
  const protectedList = config.protectedFiles.join(', ');
  const approvalList = config.approvalRequired.join(', ');
  const blockedList = config.blockedCommands.join(', ');

  if (isEn) {
    return `# Cursor AI Safety Rules

Generated by repo-seatbelt | Mode: ${config.mode}

## Protected Files - Do Not Edit
${config.protectedFiles.map(f => `- ${f}`).join('\n')}

## Requires Explicit Approval Before Editing
${config.approvalRequired.map(f => `- ${f}`).join('\n')}

## Blocked Commands - Never Run
${config.blockedCommands.map(c => `- ${c}`).join('\n')}

## Rules

- Do not edit .env files under any circumstances
- Do not delete database migration files
- Do not modify auth or payment logic without developer confirmation
- Do not run destructive database commands
- Do not add new npm/pnpm/yarn packages without asking
- Prefer small, incremental changes over large rewrites
- When in doubt, ask before acting
- If you need to touch a protected file, stop and ask the developer
- Do not rewrite files that are not related to the current task
- Check existing code patterns before introducing new abstractions

## Safety Mode: ${config.mode}
${config.mode === 'strict' ? '- Extra caution: all risky areas require explicit approval\n- Refuse to run scripts without showing them first' : ''}
${config.mode === 'team' ? '- Team mode: always flag changes to shared infrastructure\n- Prefer reversible changes' : ''}

## Project: ${config.projectType}
`;
  }

  // Turkish
  return `# Cursor AI Güvenlik Kuralları

repo-seatbelt tarafından oluşturuldu | Mod: ${config.mode}

## Korunan Dosyalar - Düzenleme Yapmayın
${config.protectedFiles.map(f => `- ${f}`).join('\n')}

## Düzenlemeden Önce Açık Onay Gerektirir
${config.approvalRequired.map(f => `- ${f}`).join('\n')}

## Engellenen Komutlar - Asla Çalıştırmayın
${config.blockedCommands.map(c => `- ${c}`).join('\n')}

## Kurallar

- Hiçbir koşulda .env dosyalarını düzenlemeyin
- Veritabanı migration dosyalarını silmeyin
- Geliştirici onayı olmadan auth veya ödeme mantığını değiştirmeyin
- Yıkıcı veritabanı komutlarını çalıştırmayın
- Sormadan yeni npm/pnpm/yarn paketi eklemeyin
- Büyük yeniden yazmalar yerine küçük, artımlı değişiklikler tercih edin
- Emin değilseniz, harekete geçmeden önce sorun
- Korunan bir dosyaya dokunmanız gerekiyorsa, durun ve geliştiriciye sorun
- Mevcut görevle ilgili olmayan dosyaları yeniden yazmayın

## Güvenlik Modu: ${config.mode}

## Proje: ${config.projectType}
`;
}
