import { RepoSeatbeltConfig } from '../types';

export function generateWindsurfRules(config: RepoSeatbeltConfig, lang: 'en' | 'tr' = 'en'): string {
  const isEn = lang === 'en';
  const protectedList = config.protectedFiles.map(f => `- ${f}`).join('\n');
  const approvalList = config.approvalRequired.map(f => `- ${f}`).join('\n');
  const blockedList = config.blockedCommands.map(c => `- ${c}`).join('\n');

  if (isEn) {
    return `# Windsurf AI Safety Rules

Generated by repo-seatbelt | Mode: ${config.mode}

## Protected Files - Never Edit
${protectedList}

## Requires Explicit Approval
${approvalList}

## Blocked Commands
${blockedList}

## Behavior
- Make the smallest change that accomplishes the goal
- Never run destructive shell commands without confirmation
- Ask before touching auth, payment, database, or production config
- Prefer reversible changes; explain risky operations before doing them
- Do not add new dependencies without asking
${config.mode === 'strict' ? '- STRICT mode: refuse to run scripts without showing them first' : ''}

## Project: ${config.projectType}
`;
  }

  return `# Windsurf AI Güvenlik Kuralları

repo-seatbelt tarafından oluşturuldu | Mod: ${config.mode}

## Korunan Dosyalar - Asla Düzenlemeyin
${protectedList}

## Açık Onay Gerektirir
${approvalList}

## Engellenen Komutlar
${blockedList}

## Davranış
- Amacı gerçekleştiren en küçük değişikliği yapın
- Yıkıcı shell komutlarını onay olmadan çalıştırmayın
- Auth, ödeme, veritabanı veya prod yapılandırmasına dokunmadan önce sorun
- Geri alınabilir değişiklikleri tercih edin
- Yeni bağımlılık eklemeden önce sorun
${config.mode === 'strict' ? '- KATI mod: scriptleri önce göstermeden çalıştırmayı reddedin' : ''}

## Proje: ${config.projectType}
`;
}
