import { RepoSeatbeltConfig } from '../types';

export function generateZedRules(config: RepoSeatbeltConfig, lang: 'en' | 'tr' = 'en'): string {
  const isEn = lang === 'en';
  const protectedList = config.protectedFiles.map(f => `- ${f}`).join('\n');
  const approvalList = config.approvalRequired.map(f => `- ${f}`).join('\n');
  const blockedList = config.blockedCommands.map(c => `- ${c}`).join('\n');

  if (isEn) {
    return `# Zed AI Assistant Rules

Generated by repo-seatbelt | Mode: ${config.mode}
Place this file at \`.rules\` in your project root.

## Do Not Modify
${protectedList}

## Ask Before Editing
${approvalList}

## Never Suggest These Commands
${blockedList}

## Style
- Match existing patterns in this repo
- Make minimal changes; avoid unrelated refactors
- Surface risks but do not silently fix things outside scope
- Do not introduce new dependencies without confirmation

Project: ${config.projectType} | Safety mode: ${config.mode}
`;
  }

  return `# Zed AI Asistan Kuralları

repo-seatbelt tarafından oluşturuldu | Mod: ${config.mode}
Bu dosyayı projenin kök dizininde \`.rules\` olarak yerleştirin.

## Değiştirmeyin
${protectedList}

## Düzenlemeden Önce Sorun
${approvalList}

## Bu Komutları Asla Önermeyin
${blockedList}

## Stil
- Mevcut depo paternlerine uyum sağlayın
- Minimal değişiklik yapın; ilgisiz refactor'lardan kaçının
- Riskleri belirtin ama kapsam dışı şeyleri sessizce düzeltmeyin
- Onay olmadan yeni bağımlılık eklemeyin

Proje: ${config.projectType} | Güvenlik modu: ${config.mode}
`;
}
