import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { t, setLang } from '../i18n';
import { Lang, ScanResult, RiskItem } from '../types';
import { readConfig } from '../config';
import { runScan } from '../scanners';
import { getScoreLabel } from '../scoring';
import { printHeader } from '../display/renderer';

interface ReportOptions {
  lang?: string;
  output?: string;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString();
}

function riskEmoji(level: string): string {
  if (level === 'high') return '🔴';
  if (level === 'medium') return '🟡';
  if (level === 'low') return '🟢';
  return 'ℹ️';
}

function generateMarkdown(result: ScanResult, lang: Lang): string {
  const isEn = lang === 'en';
  const scoreLabel = getScoreLabel(result.score, lang);
  const date = formatDate(result.timestamp);

  const highRisks = result.risks.filter(r => r.level === 'high');
  const mediumRisks = result.risks.filter(r => r.level === 'medium');
  const lowRisks = result.risks.filter(r => r.level === 'low');

  function riskSection(risks: RiskItem[], levelLabel: string): string {
    if (risks.length === 0) return '';
    return `### ${levelLabel}\n\n${risks.map(r =>
      `- **${r.message}**${r.recommendation ? `\n  > ${r.recommendation}` : ''}`
    ).join('\n\n')}\n\n`;
  }

  const rollbackItems = isEn ? [
    'Review full git diff before committing',
    'Revert risky files first (.env, migrations, auth)',
    'Check environment files are intact',
    'Run full test suite',
    'Run build',
    'Verify auth and payment flows manually',
    'Commit only after review',
  ] : [
    'Commit etmeden önce tam git diff\'i gözden geçirin',
    'Riskli dosyaları önce geri alın (.env, migrations, auth)',
    'Ortam dosyalarının sağlam olduğunu kontrol edin',
    'Tüm test paketini çalıştırın',
    'Build alın',
    'Kimlik doğrulama ve ödeme akışlarını manuel olarak doğrulayın',
    'İncelemeden sonra commit yapın',
  ];

  if (isEn) {
    return `# repo-seatbelt - AI Safety Report

> Generated on ${date}

## AI Safety Score

**${result.score} / 100** - ${scoreLabel}

## Project Info

| Property | Value |
|----------|-------|
| Framework | ${result.projectInfo.framework.join(', ') || 'Unknown'} |
| Package Manager | ${result.projectInfo.packageManager} |
| Database | ${result.projectInfo.databases.join(', ') || 'None detected'} |
| Auth | ${result.projectInfo.authProviders.join(', ') || 'None detected'} |
| Payment | ${result.projectInfo.paymentProviders.join(', ') || 'None detected'} |
| Has Tests | ${result.projectInfo.hasTests ? 'Yes ✓' : 'No ✗'} |
| Has README | ${result.projectInfo.hasReadme ? 'Yes ✓' : 'No ✗'} |
| Safety Mode | ${result.config?.mode ?? 'Not configured'} |

## AI Rules Status

| Rule File | Status |
|-----------|--------|
| .repo-seatbelt.json | ${result.aiRulesStatus.hasConfig ? '✓ Found' : '✗ Missing'} |
| CLAUDE.md | ${result.aiRulesStatus.hasCLAUDEMD ? '✓ Found' : '✗ Missing'} |
| AGENTS.md | ${result.aiRulesStatus.hasAGENTSMD ? '✓ Found' : '✗ Missing'} |
| Cursor rules | ${result.aiRulesStatus.hasCursorRules ? '✓ Found' : '✗ Missing'} |

## Risk Summary

Total risks: ${result.risks.length} (${highRisks.length} high, ${mediumRisks.length} medium, ${lowRisks.length} low)

${riskSection(highRisks, '🔴 High Risk')}${riskSection(mediumRisks, '🟡 Medium Risk')}${riskSection(lowRisks, '🟢 Low Risk')}

## Rollback Checklist

Before committing AI-generated changes, verify:

${rollbackItems.map(item => `- [ ] ${item}`).join('\n')}

---

*Generated by [repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt)*
`;
  }

  // Turkish
  return `# repo-seatbelt - AI Güvenlik Raporu

> ${date} tarihinde oluşturuldu

## AI Güvenlik Puanı

**${result.score} / 100** - ${scoreLabel}

## Proje Bilgileri

| Özellik | Değer |
|---------|-------|
| Framework | ${result.projectInfo.framework.join(', ') || 'Bilinmiyor'} |
| Paket Yöneticisi | ${result.projectInfo.packageManager} |
| Veritabanı | ${result.projectInfo.databases.join(', ') || 'Tespit edilmedi'} |
| Auth | ${result.projectInfo.authProviders.join(', ') || 'Tespit edilmedi'} |
| Ödeme | ${result.projectInfo.paymentProviders.join(', ') || 'Tespit edilmedi'} |
| Test Var mı | ${result.projectInfo.hasTests ? 'Evet ✓' : 'Hayır ✗'} |
| README Var mı | ${result.projectInfo.hasReadme ? 'Evet ✓' : 'Hayır ✗'} |
| Güvenlik Modu | ${result.config?.mode ?? 'Yapılandırılmamış'} |

## AI Kural Durumu

| Kural Dosyası | Durum |
|---------------|-------|
| .repo-seatbelt.json | ${result.aiRulesStatus.hasConfig ? '✓ Bulundu' : '✗ Eksik'} |
| CLAUDE.md | ${result.aiRulesStatus.hasCLAUDEMD ? '✓ Bulundu' : '✗ Eksik'} |
| AGENTS.md | ${result.aiRulesStatus.hasAGENTSMD ? '✓ Bulundu' : '✗ Eksik'} |
| Cursor kuralları | ${result.aiRulesStatus.hasCursorRules ? '✓ Bulundu' : '✗ Eksik'} |

## Risk Özeti

Toplam risk: ${result.risks.length} (${highRisks.length} yüksek, ${mediumRisks.length} orta, ${lowRisks.length} düşük)

${riskSection(highRisks, '🔴 Yüksek Risk')}${riskSection(mediumRisks, '🟡 Orta Risk')}${riskSection(lowRisks, '🟢 Düşük Risk')}

## Geri Alma Kontrol Listesi

AI tarafından oluşturulan değişiklikleri commit etmeden önce doğrulayın:

${rollbackItems.map(item => `- [ ] ${item}`).join('\n')}

---

*[repo-seatbelt](https://github.com/berkcangumusisik/repo-seatbelt) tarafından oluşturuldu*
`;
}

export async function reportCommand(options: ReportOptions): Promise<void> {
  const cwd = process.cwd();
  const config = readConfig(cwd);
  const lang = ((options.lang as Lang) || config?.language || 'en') as Lang;
  setLang(lang);

  printHeader(t('report.title'));

  const spinner = ora({
    text: chalk.dim(t('report.generating')),
    spinner: 'dots',
    color: 'cyan',
  }).start();

  try {
    const result = await runScan(cwd);
    const markdown = generateMarkdown(result, lang);

    const outputPath = options.output ?? path.join(cwd, 'docs', 'repo-seatbelt-report.md');
    const dir = path.dirname(outputPath);

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, markdown, 'utf-8');
    spinner.stop();

    console.log(chalk.green('  ✓  ') + t('report.saved', { path: outputPath }));
    console.log();
  } catch (err) {
    spinner.stop();
    const msg = err instanceof Error ? err.message : String(err);
    console.error(chalk.red(`  ✗  ${t('errors.general', { message: msg })}`));
    process.exit(1);
  }
}
